/**
 * TWCore Diagnostics Api
 * TWCore diagnostics api
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface LogLevelQuantity {
    name?: LogLevelQuantity.NameEnum;
    count?: number;
}
export namespace LogLevelQuantity {
    export type NameEnum = 'Error' | 'Warning' | 'InfoBasic' | 'InfoMedium' | 'InfoDetail' | 'Debug' | 'Verbose' | 'Stats' | 'LibDebug' | 'LibVerbose';
    export const NameEnum = {
        Error: 'Error' as NameEnum,
        Warning: 'Warning' as NameEnum,
        InfoBasic: 'InfoBasic' as NameEnum,
        InfoMedium: 'InfoMedium' as NameEnum,
        InfoDetail: 'InfoDetail' as NameEnum,
        Debug: 'Debug' as NameEnum,
        Verbose: 'Verbose' as NameEnum,
        Stats: 'Stats' as NameEnum,
        LibDebug: 'LibDebug' as NameEnum,
        LibVerbose: 'LibVerbose' as NameEnum
    };
}
