/**
 * TWCore Diagnostics Api
 * TWCore diagnostics api
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ApplicationsLevels } from './applicationsLevels';
import { LogLevelTimes } from './logLevelTimes';


export interface LogSummary {
    applications?: Array<ApplicationsLevels>;
    levels?: Array<LogLevelTimes>;
}
