/**
 * TWCore Diagnostics Api
 * TWCore diagnostics api
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NodeTraceItem {
    traceId?: string;
    tags?: string;
    group?: string;
    name?: string;
    timestamp?: Date;
    instanceId?: string;
    id?: string;
    environment?: string;
    machine?: string;
    application?: string;
}
