/**
 * TWCore Diagnostics Api
 * TWCore diagnostics api
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NodeStatusItemValue {
    key?: string;
    value?: any;
    type?: NodeStatusItemValue.TypeEnum;
}
export namespace NodeStatusItemValue {
    export type TypeEnum = 'Text' | 'Number' | 'Date' | 'Time' | 'Array';
    export const TypeEnum = {
        Text: 'Text' as TypeEnum,
        Number: 'Number' as TypeEnum,
        Date: 'Date' as TypeEnum,
        Time: 'Time' as TypeEnum,
        Array: 'Array' as TypeEnum
    }
}
