/**
 * TWCore Diagnostics Api
 * TWCore diagnostics api
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NodeStatusItemValue } from './nodeStatusItemValue';


export interface NodeStatusItem {
    applicationDisplayName?: string;
    elapsedMilliseconds?: number;
    date?: Date;
    startTime?: Date;
    timestamp?: Date;
    values?: Array<NodeStatusItemValue>;
    instanceId?: string;
    id?: string;
    environment?: string;
    machine?: string;
    application?: string;
}
