/**
 * TWCore Diagnostics Api
 * TWCore diagnostics api
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NodeTraceItem } from './nodeTraceItem';


export interface PagedListNodeTraceItem {
    pageNumber?: number;
    pageSize?: number;
    totalResults?: number;
    data?: Array<NodeTraceItem>;
}
