/**
 * TWCore Diagnostics Api
 * TWCore diagnostics api
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TraceResult } from './traceResult';


export interface PagedListTraceResult {
    pageNumber?: number;
    pageSize?: number;
    totalResults?: number;
    totalPages?: number;
    data?: Array<TraceResult>;
}


