/**
 * TWCore Diagnostics Api
 * TWCore diagnostics api
 *
 * OpenAPI spec version: v1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NodeLogItem } from './nodeLogItem';
import { NodeTraceItem } from './nodeTraceItem';
import { SerializableException } from './serializableException';

export interface SearchResults {
    logs?: Array<NodeLogItem>;
    traces?: Array<NodeTraceItem>;
    data?: Array<NodeInfo>;
}
export interface NodeInfo {
    logId?: string;
    assembly?: string;
    type?: string;
    group?: string;
    code?: string;
    level?: NodeLogItem.LevelEnum;
    message?: string;
    exception?: SerializableException;
    timestamp?: Date;
    instanceId?: string;
    id?: string;
    environment?: string;
    machine?: string;
    application?: string;

    traceId?: string;
    tags?: string;
    name?: string;
    formats?: string[];
}
